import { escapeHtml, pageShell, publicName, responseHtml } from './_lib/render';

type Env = { SUPABASE_URL: string; SUPABASE_ANON_KEY: string };
type Category = { slug: string; title_bn: string };
type Profile = { username: string; display_name: string; avatar_url: string | null };
type Story = { id: string; slug: string; title: string; excerpt: string; body: string; author_id: string; published_at: string; hero_media_key: string | null; category: Category | Category[]; profiles: Profile | Profile[] };
const one = <T,>(value: T | T[] | null | undefined): T | null => Array.isArray(value) ? value[0] ?? null : value ?? null;
const formatTime = (value: string) => {
  const elapsed = Math.max(0, Date.now() - new Date(value).getTime());
  const hours = Math.floor(elapsed / 3_600_000);
  if (hours < 1) return 'এইমাত্র';
  if (hours < 24) return `${new Intl.NumberFormat('bn-BD').format(hours)} ঘণ্টা আগে`;
  return new Date(value).toLocaleDateString('bn-BD', { day: 'numeric', month: 'short' });
};
const slugClass = (value: string) => value.includes('culture') || value.includes('opinion') ? 'art-culture' : value.includes('university') ? 'art-library' : value.includes('student') ? 'art-student' : 'art-campus';

function card(story: Story, rank: number) {
  const category = one(story.category) ?? { slug: 'campus', title_bn: 'ক্যাম্পাস' };
  const author = one(story.profiles) ?? { username: '', display_name: 'সম্পাদকীয় ডেস্ক', avatar_url: null };
  const url = `/news/${encodeURIComponent(story.slug)}/`;
  return `<article class="story-card" data-story-card data-story-id="${escapeHtml(story.id)}"><a class="story-card__art story-art" href="${url}" aria-label="প্রতিবেদন পড়ুন: ${escapeHtml(story.title)}"><span class="story-art__visual ${slugClass(category.slug)}"><span class="story-art__halo"></span><span class="story-art__line story-art__line--one"></span><span class="story-art__line story-art__line--two"></span><span class="story-art__seal">ঢা<br><i>বি</i></span><span class="story-art__pill">ঢাকা বিশ্ববিদ্যালয়</span></span><span class="story-card__category">${escapeHtml(category.title_bn)}</span></a><div class="story-card__body"><div class="story-meta"><a href="/category/${encodeURIComponent(category.slug)}/">${escapeHtml(category.title_bn)}</a><span aria-hidden="true">·</span><time datetime="${escapeHtml(story.published_at)}">${escapeHtml(formatTime(story.published_at))}</time></div><h3><a href="${url}">${escapeHtml(story.title)}</a></h3><p>${escapeHtml(story.excerpt)}</p><div class="story-card__footer"><a class="story-byline" href="/u/${encodeURIComponent(author.username)}/">${escapeHtml(publicName(author))}</a><a class="round-arrow" href="${url}" aria-label="প্রতিবেদন পড়ুন"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M12 5l7 7-7 7"/></svg></a></div></div></article>`;
}

export const onRequestGet: PagesFunction<Env> = async ({ request, env }) => {
  const canonical = '/';
  if (!env.SUPABASE_URL || !env.SUPABASE_ANON_KEY || env.SUPABASE_URL.includes('YOUR_PROJECT_REF')) {
    return fetch(new URL('/', request.url), { headers: { 'Accept': 'text/html' } });
  }
  const feedUrl = new URL('/rest/v1/articles', `${env.SUPABASE_URL.replace(/\/$/, '')}/`);
  feedUrl.searchParams.set('select', 'id,slug,title,excerpt,body,author_id,published_at,hero_media_key,category:categories(slug,title_bn),profiles:profiles!articles_author_id_fkey(username,display_name,avatar_url)');
  feedUrl.searchParams.set('status', 'eq.published');
  feedUrl.searchParams.set('order', 'published_at.desc');
  feedUrl.searchParams.set('limit', '25');
  const result = await fetch(feedUrl, { headers: { apikey: env.SUPABASE_ANON_KEY, Authorization: `Bearer ${env.SUPABASE_ANON_KEY}` } });
  if (!result.ok) return fetch(new URL('/', request.url), { headers: { 'Accept': 'text/html' } });
  const stories = await result.json() as Story[];
  const featured = stories[0];
  const side = stories.slice(1, 7);
  const featuredCategory = featured ? one(featured.category) ?? { slug: 'campus', title_bn: 'ক্যাম্পাস' } : null;
  const featuredImage = featured?.hero_media_key ? `<img class="server-lead-image" src="https://media.dutimz.com/media/${encodeURIComponent(featured.hero_media_key)}" alt="" loading="eager">` : `<span class="story-art__visual story-art__visual--lead ${slugClass(featuredCategory?.slug ?? 'campus')}"><span class="story-art__halo"></span><span class="story-art__line story-art__line--one"></span><span class="story-art__line story-art__line--two"></span><span class="story-art__seal story-art__seal--lead">ঢা<br><i>বি</i></span><span class="lead-art__caption"><span class="lead-art__live-dot"></span> ঢাকা বিশ্ববিদ্যালয়ের কথা</span></span>`;
  const featuredMarkup = featured && featuredCategory
    ? `<article class="lead-story" data-featured-story data-story-id="${escapeHtml(featured.id)}"><div class="lead-story__copy"><span class="lead-label"><span class="lead-label__mark">ঢা</span> আজকের মুখ্য প্রতিবেদন</span><div class="lead-story__meta"><a href="/category/${encodeURIComponent(featuredCategory.slug)}/">${escapeHtml(featuredCategory.title_bn)}</a><span aria-hidden="true">·</span><time datetime="${escapeHtml(featured.published_at)}">${escapeHtml(formatTime(featured.published_at))}</time></div><h1 id="featured-title"><a href="/news/${encodeURIComponent(featured.slug)}/">${escapeHtml(featured.title)}</a></h1><p>${escapeHtml(featured.excerpt)}</p><div class="lead-story__tags"><span>#ঢাকাবিশ্ববিদ্যালয়</span><span>#${escapeHtml(featuredCategory.title_bn)}</span></div><a class="read-button" href="/news/${encodeURIComponent(featured.slug)}/"><span>প্রতিবেদন পড়ুন</span><span class="read-button__arrow" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 12h13M12 5l7 7-7 7"/></svg></span></a></div><a class="lead-art story-art" href="/news/${encodeURIComponent(featured.slug)}/" aria-label="প্রতিবেদন পড়ুন: ${escapeHtml(featured.title)}"><span class="story-art__visual--lead ${slugClass(featuredCategory.slug)}"></span>${featuredImage}<span class="lead-art__stamp">ঢাকা<br>বিশ্ববিদ্যালয়</span></a></article>`
    : `<section class="lead-story lead-story--empty"><div class="lead-story__copy"><span class="lead-label"><span class="lead-label__mark">ঢা</span> ক্যাম্পাসের খবর, ক্যাম্পাসের কণ্ঠে</span><h1 id="featured-title">ঢাকা বিশ্ববিদ্যালয়ের প্রতিটি গল্পের নিজস্ব একটি মঞ্চ।</h1><p>ক্যাম্পাসের সংবাদ, শিক্ষার্থীদের কণ্ঠ, সংস্কৃতি ও মতামত—সম্পাদিত ও যাচাই করা প্রতিবেদন পড়ুন ডুটিমজে।</p><a class="read-button" href="/account/write/"><span>আপনার প্রতিবেদন পাঠান</span><span class="read-button__arrow">→</span></a></div><div class="lead-art lead-art--placeholder" aria-hidden="true"><span class="placeholder-seal">ঢা<br><i>বি</i></span><span class="placeholder-ring placeholder-ring--one"></span><span class="placeholder-ring placeholder-ring--two"></span><span class="placeholder-caption">ক্যাম্পাসের কণ্ঠস্বর</span></div></section>`;
  const cards = side.length ? side.slice(0, 3).map((story, index) => card(story, index + 1)).join('') : '<div class="feed-empty"><span class="feed-empty__icon">ঢা</span><strong>প্রথম প্রতিবেদনটি আসছে</strong><p>সম্পাদকীয় ডেস্কের যাচাই করা খবর এখানে দেখানো হবে।</p></div>';
  const recommended = side.length ? side.slice(0, 1).map((story) => `<a class="recommended-feature__art story-art" href="/news/${encodeURIComponent(story.slug)}/"><span class="story-art__visual ${slugClass(one(story.category)?.slug ?? '')}"><span class="story-art__halo"></span><span class="story-art__seal">ঢা<br><i>বি</i></span><span class="recommended-feature__copy"><span>${escapeHtml(one(story.category)?.title_bn ?? 'ক্যাম্পাস')} · ${escapeHtml(formatTime(story.published_at))}</span><strong>${escapeHtml(story.title)}</strong></span></span></a>`).join('') : '';
  const recommendedList = side.slice(1, 6).map((story) => {
    const category = one(story.category) ?? { slug: 'campus', title_bn: 'ক্যাম্পাস' };
    return `<article class="recommended-item"><a href="/news/${encodeURIComponent(story.slug)}/" class="recommended-item__copy"><span class="story-meta"><span>${escapeHtml(category.title_bn)}</span><span aria-hidden="true">·</span><time>${escapeHtml(formatTime(story.published_at))}</time></span><h3>${escapeHtml(story.title)}</h3></a><a class="recommended-thumb story-art__visual ${slugClass(category.slug)}" href="/news/${encodeURIComponent(story.slug)}/" aria-label="প্রতিবেদন পড়ুন"><span class="story-art__seal">ঢা</span></a></article>`;
  }).join('');
  const content = `<div class="portal-frame"><div class="portal-grid"><section class="editorial-main" aria-labelledby="featured-title"><div class="section-eyebrow"><span class="eyebrow-dot"></span> ক্যাম্পাসের খবর, ক্যাম্পাসের কণ্ঠে</div>${featuredMarkup}<div class="feed-heading"><div><span class="section-kicker">সাম্প্রতিক</span><h2>ক্যাম্পাসের খবর</h2></div><a class="text-link" href="/search/">সব খবর দেখুন <span>→</span></a></div><div class="story-grid" id="story-feed">${cards}</div><section class="contribute-card"><span class="contribute-card__symbol" aria-hidden="true">✳</span><div><span class="section-kicker">ক্যাম্পাসের খবর আপনার চোখেও?</span><h2>আপনার গল্পটিও বলুন।</h2><p>ঢাকা বিশ্ববিদ্যালয়ের যেকোনো শিক্ষার্থী বা পাঠক প্রতিবেদন পাঠাতে পারেন।</p></div><a class="contribute-link" href="/account/write/">প্রতিবেদন পাঠান ↗</a></section></section><aside class="recommendation-panel" aria-labelledby="recommend-title"><form class="sidebar-search" action="/search/" role="search"><label class="sr-only" for="sidebar-search-input">প্রতিবেদন খুঁজুন</label><input id="sidebar-search-input" name="q" type="search" placeholder="নাম, বিষয় বা বিভাগ খুঁজুন…"><button type="submit" aria-label="খুঁজুন">⌕</button></form><div class="sidebar-heading"><div><span class="section-kicker">পাঠকের পছন্দ</span><h2 id="recommend-title">আরও পড়ুন</h2></div><a href="/search/">সব <span>›</span></a></div><div class="recommended-feature">${recommended}</div><div class="recommended-list">${recommendedList}</div><section class="sidebar-topics"><div class="sidebar-heading"><div><span class="section-kicker">আলোচনায়</span><h2>আজকের বিষয়</h2></div></div><a href="/category/campus/" class="topic-chip"><span>#</span> ক্যাম্পাস জীবন</a><a href="/category/university/" class="topic-chip"><span>#</span> বিশ্ববিদ্যালয়</a><a href="/category/culture/" class="topic-chip"><span>#</span> সংস্কৃতি</a></section><section class="newsletter-card"><span class="newsletter-icon">✦</span><span class="section-kicker">ক্যাম্পাসের খবর</span><h2>গুরুত্বপূর্ণ গল্পগুলো পড়ুন একসাথে।</h2><p>গুগল দিয়ে প্রবেশ করুন; সংরক্ষিত খবর থাকবে নিজের প্রোফাইলে।</p><a class="newsletter-button" href="/auth/sign-in/">গুগল দিয়ে প্রবেশ <span>→</span></a></section></aside></div></div>`;
  const html = pageShell('ঢাকা বিশ্ববিদ্যালয়ের সংবাদমাধ্যম', 'ঢাকা বিশ্ববিদ্যালয়ের ক্যাম্পাস সংবাদ, শিক্ষার্থী জীবন, সংস্কৃতি, মতামত ও বিশ্ববিদ্যালয়ের গল্প—ডুটিমজে।', canonical, content);
  return responseHtml(html, 200, 'public, max-age=30, stale-while-revalidate=120');
};
